export const GET_JUGADOR = "GET_JUGADOR";
export const GET_JUGADORES = "GET_JUGADORES";
export const POST_JUGADOR_SUCCESS = "POST_JUGADOR_SUCCESS";
export const DELETE_JUGADOR = "DELETE_JUGADOR";
export const UPDATE_JUGADOR = "UPDATE_JUGADOR";
export const JUGADOR_ERROR = "JUGADOR_ERROR";
